// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7WKGlWfVU04LaenAsHgofIA9MZpHfcjw',
    appId: '1:290133130633:web:be84a16177b8bc84a23558',
    messagingSenderId: '290133130633',
    projectId: 'flutter-chat-app-32a34',
    authDomain: 'flutter-chat-app-32a34.firebaseapp.com',
    storageBucket: 'flutter-chat-app-32a34.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwvuWTZTqHn8_hTDxZOPLBoAdr9d6vBds',
    appId: '1:290133130633:android:f54b2e7f3df87feca23558',
    messagingSenderId: '290133130633',
    projectId: 'flutter-chat-app-32a34',
    storageBucket: 'flutter-chat-app-32a34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvb4XeIi1A1sKcH7A9fw-TTJPtDikr-kA',
    appId: '1:290133130633:ios:3c0818930a5fd899a23558',
    messagingSenderId: '290133130633',
    projectId: 'flutter-chat-app-32a34',
    storageBucket: 'flutter-chat-app-32a34.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvb4XeIi1A1sKcH7A9fw-TTJPtDikr-kA',
    appId: '1:290133130633:ios:3c0818930a5fd899a23558',
    messagingSenderId: '290133130633',
    projectId: 'flutter-chat-app-32a34',
    storageBucket: 'flutter-chat-app-32a34.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7WKGlWfVU04LaenAsHgofIA9MZpHfcjw',
    appId: '1:290133130633:web:cadb1ff1f100162ca23558',
    messagingSenderId: '290133130633',
    projectId: 'flutter-chat-app-32a34',
    authDomain: 'flutter-chat-app-32a34.firebaseapp.com',
    storageBucket: 'flutter-chat-app-32a34.appspot.com',
  );

}